/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorkOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Text,
  'notes' : IDL.Text,
  'dateOfWork' : IDL.Text,
  'workerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'createWorkOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteWorkOrder' : IDL.Func([IDL.Nat], [], []),
  'getWorkOrder' : IDL.Func([IDL.Nat], [WorkOrder], ['query']),
  'getWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
  'getWorkOrdersByStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkOrder)],
      ['query'],
    ),
  'getWorkOrdersByWorker' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkOrder)],
      ['query'],
    ),
  'updateWorkOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorkOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Text,
    'notes' : IDL.Text,
    'dateOfWork' : IDL.Text,
    'workerName' : IDL.Text,
  });
  
  return IDL.Service({
    'createWorkOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteWorkOrder' : IDL.Func([IDL.Nat], [], []),
    'getWorkOrder' : IDL.Func([IDL.Nat], [WorkOrder], ['query']),
    'getWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
    'getWorkOrdersByStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkOrder)],
        ['query'],
      ),
    'getWorkOrdersByWorker' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkOrder)],
        ['query'],
      ),
    'updateWorkOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };